service: dolphin-backend
frameworkVersion: "=1.74.1"
provider:
  name: aws
  runtime: python3.8

functions:
  ping:
    handler: handler.ping
    events:
     - http:
         path: ping
         method: get
  create_note:
    handler: handler.create_note
    events:
     - http:
         path: ping
         method: get
  update_note:
    handler: handler.update_note
    events:
     - http:
         path: ping
         method: post
  destroy_note:
    handler: handler.destroy_note
    events:
     - http:
         path: ping
         method: post
