name: Deploy

on:
  push:
    branches: [ master, develop ]
    paths-ignore:
    - 'backend/**'
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Deploy
      shell: bash
      env:
        CICD: "*"
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        GOOGLE_POOL_ID_PROD: ${{ secrets.GOOGLE_POOL_ID_PROD }}
        GOOGLE_POOL_SECRET_PROD: ${{ secrets.GOOGLE_POOL_SECRET_PROD }}
        GOOGLE_POOL_ID_DEV: ${{ secrets.GOOGLE_POOL_ID_DEV }}
        GOOGLE_POOL_SECRET_DEV: ${{ secrets.GOOGLE_POOL_SECRET_DEV }}
      run: |
        ./deploy.sh -e ${GITHUB_REF##*/}
        